# Generated by Django 3.2.11 on 2022-02-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='店舗投稿者のIPアドレス'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='レビュー投稿者のIPアドレス'),
            preserve_default=False,
        ),
    ]
