# Generated by Django 3.2.11 on 2022-02-25 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurant_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='お問い合わせタイトル')),
                ('content', models.CharField(max_length=1000, verbose_name='お問い合わせ本文')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='お問い合わせ日時')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('ip', models.GenericIPAddressField(verbose_name='お問い合わせ投稿者のIPアドレス')),
            ],
        ),
    ]
