# Generated by Django 3.2.10 on 2022-03-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='test.png', upload_to='icon/', verbose_name='カテゴリアイコン'),
            preserve_default=False,
        ),
    ]
